version: "3.8"
services:
  server:
    build:
      dockerfile: crawler/Dockerfile
      context: ../
    volumes:
      - ./output:/app/output
    ports:
      - "3000:3000"
    env_file:
      - .env
