version: "3.8"

networks:
  my-bridge-network:
    driver: bridge
    
services:
  crawler-server:
    build:
      dockerfile: crawler/Dockerfile
      context: ../
    volumes:
      - ./output:/usr/src/app/output
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - my-bridge-network
